import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    metadataBase: new URL("https://www.sifat.online"),
    title: "MD: ABDUR RAHMAN SIFAT || Sanity Studio",
    description: "Generated by sifat khan",
    icons: {
        icon: '/Sifat.svg',
    },
    openGraph: {
        title: "MD: ABDUR RAHMAN SIFAT || Sanity Studio",
        description: "Generated by sifat khan",
        siteName: "MD: ABDUR RAHMAN SIFAT || Sanity Studio",
        images: [
            {
                url: '/opengraph-image.png',
                width: 1200,
                height: 630,
                alt: 'MD: ABDUR RAHMAN SIFAT || Sanity Studio',
            },
        ],
    },
};

function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}

export default Layout;
